name: CI-CD to ECS

on:
  push:
    branches: [ "master" ]   # or whichever branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Log in to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build & Push the image to ECR
      - name: Build, Tag, and Push Image
        id: build-image
        run: |
          # Set a few variables
          IMAGE_NAME=fedseek
          ECR_REGISTRY=$(aws ecr describe-repositories --repository-names $IMAGE_NAME --query 'repositories[0].repositoryUri' --output text)
          IMAGE_TAG=${GITHUB_SHA::7}          # short commit hash, or "latest"

          echo "ECR Registry: $ECR_REGISTRY"
          echo "Image Tag: $IMAGE_TAG"

          # Build the Docker image
          docker build -t $IMAGE_NAME:${IMAGE_TAG} .
          
          # Tag the image for ECR
          docker tag $IMAGE_NAME:${IMAGE_TAG} $ECR_REGISTRY:${IMAGE_TAG}
          
          # Push to ECR
          docker push $ECR_REGISTRY:${IMAGE_TAG}

          # Write image URI to GitHub Actions output
          echo "::set-output name=image::$ECR_REGISTRY:${IMAGE_TAG}"

      # 5. Deploy to ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          # The cluster and service you want to deploy to
          cluster: ECS-FedSeek-ECS-1LPUU94C8V607
          service: MyECSService-FedSeek-ECS-1LPUU94C8V607
          
          # Path to your Task Definition JSON in your repo
          # or you can reference a pre-registered task definition ARN.
          task-definition: "arn:aws:ecs:us-east-1:703671924104:task-definition/FedSeekTaskDef:17"
          
          # The name of the container in your ECS task definition that should receive the new image
          container-name: "fedseek-container"
          
          # Use the new image from the step above
          container-image: ${{ steps.build-image.outputs.image }}
